---
- hosts: all
  #remote_user: root

  pre_tasks:
    - name: Ensure build dependencies are installed (RedHat)
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - "@Development tools"
        - tar
        - unzip
        - sudo
        - which
      when: ansible_os_family == 'RedHat'

  roles:
    - ansible-tinc
